CREATE TABLE IF NOT EXISTS contact_submissions (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  phone VARCHAR(20),
  message TEXT,
  budget VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);